extensions/spree_invoicing-master/config/routes.rb
Spree::Core::Engine.routes.draw do

 # Add your extension routes here
  namespace :admin do
    resource :company_settings
  end

end

extensions/spree_invoicing-master/app/models/spree/address_decorator.rb
Spree::Address.class_eval do
  attr_accessible  :vat_number
  #validates :vat_number, presence: true
end

extensions/spree_invoicing-master/app/models/spree/company_configuration.rb
##Added Company Information with Prefernces
class Spree::CompanyConfiguration < Spree::Preferences::Configuration
  preference :company_name, :string
  preference :company_slogan, :string
  preference :company_address_number, :string
  preference :company_street, :string
  preference :company_city, :string
  preference :company_zip, :string
  preference :company_phone, :string
  preference :company_fax, :string
  preference :company_email, :string
  preference :company_website ,:string
  preference :company_vatnumber,:string
  

  preference :company_beneficiary, :string
  preference :company_bankname, :string
  preference :company_branchname, :string
  preference :company_account_number ,:string
  preference :company_rtgscode,:string

end

extensions/spree_invoicing-master/app/models/spree/print_invoice_configuration.rb
#Invoice Print Configurations
#Spree::Config[:admin_interface_logo]

module Spree
  class PrintInvoiceConfiguration < Preferences::Configuration
    preference :print_invoice_logo_path, :string, :default => Spree::Config[:admin_interface_logo]
    preference :print_buttons, :string, :default => 'invoice' 
  end
end

extensions/spree_invoicing-master/app/models/spree/user_decorator.rb
Spree::User.class_eval do
    attr_accessible  :language

#Validation for Language
    validates :language, presence: true

end

extensions/spree_invoicing-master/app/controllers/base_controller_decorator.rb
Spree::BaseController.class_eval do
  before_filter :set_locale

  def set_locale
    if spree_current_user && session[:locale] != params[:locale]
      session[:locale] = spree_current_user.language if spree_current_user.language
    end
    session[:locale] = params[:locale] if params[:locale]
  end

end

extensions/spree_invoicing-master/app/controllers/spree/admin/company_settings_controller.rb
module Spree
  module Admin
    class CompanySettingsController < BaseController
      def update
        Spree::Company::Config.set(params[:preferences])

        respond_to do |format|
          format.html {
            redirect_to edit_admin_company_settings_path
          }
        end
      end
    end
  end
end

extensions/spree_invoicing-master/app/controllers/spree/admin/orders_controller_decorator.rb
Spree::Admin::OrdersController.class_eval do
  respond_to :pdf
  require "prawn"
  require "prawn/layout"
 def show
 	load_order
   @order = order.find(params[:number])
   respond_to do |format|
     format.pdf do
        pdf = Prawn::Document.new(@order)
        send_data pdf.render, filename: "order_#{}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
     end
   end
 end

end

extensions/spree_invoicing-master/app/views/spree/admin/company_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
    <%= Spree.t('company.company_settings') %>
<% end %>

<%= form_tag(admin_company_settings_path, :method => :put) do |f| -%>

    <fieldset class="no-border-top">
        
         <h3>Company Details</h3>
         <hr>
         <br>
      <div data-hook="admin_company_settings" class="row">

        <div data-hook="company_name" class="field">
          <label><%= Spree.t('company.company_name') %></label><br>
          <%= text_field_tag('preferences[company_name]', Spree::Company::Config[:company_name], :size => 40) %>
        </div>


        <div data-hook="company_slogan" class="field">
          <label><%= Spree.t('company.company_slogan') %></label><br>
          <%= text_field_tag('preferences[company_slogan]', Spree::Company::Config[:company_slogan], :size => 40) %>
        </div>

        <div data-hook="company_address_number" class="field">
          <label><%= Spree.t('company.company_address_number') %></label><br>
          <%= text_field_tag('preferences[company_address_number]', Spree::Company::Config[:company_address_number], :size => 40) %>
        </div>

        <div data-hook="company_street" class="field">
          <label><%= Spree.t('company.company_street') %></label><br>
          <%= text_field_tag('preferences[company_street]', Spree::Company::Config[:company_street], :size => 40) %>
        </div>

        <div data-hook="company_city" class="field">
          <label><%= Spree.t('company.company_city') %></label><br>
          <%= text_field_tag('preferences[company_city]', Spree::Company::Config[:company_city], :size => 40) %>
        </div>

        <div data-hook="company_zip" class="field">
          <label><%= Spree.t('company.company_zip') %></label><br>
          <%= text_field_tag('preferences[company_zip]', Spree::Company::Config[:company_zip], :size => 40) %>
        </div>

        <div data-hook="company_phone" class="field">
          <label><%= Spree.t('company.company_phone') %></label><br>
          <%= text_field_tag('preferences[company_phone]', Spree::Company::Config[:company_phone], :size => 40) %>
        </div>

        <div data-hook="company_fax" class="field">
          <label><%= Spree.t('company.company_fax') %></label><br>
          <%= text_field_tag('preferences[company_fax]', Spree::Company::Config[:company_fax], :size => 40) %>
        </div>

        <div data-hook="company_email" class="field">
          <label><%= Spree.t('company.company_email') %></label><br>
          <%= text_field_tag('preferences[company_email]', Spree::Company::Config[:company_email], :size => 40) %>
        </div>


        <div data-hook="company_website" class="field">
          <label><%= Spree.t('company.company_website') %></label><br>
          <%= text_field_tag('preferences[company_website]', Spree::Company::Config[:company_website], :size => 40) %>
        </div>

        <div data-hook="company_vatnumber" class="field">
          <label><%= Spree.t('company.company_vatnumber') %></label><br>
          <%= text_field_tag('preferences[company_vatnumber]', Spree::Company::Config[:company_vatnumber], :size => 40) %>
        </div>

         <br>
         <h3>Company Bank Account Details</h3>
         <hr>
        <div data-hook="company_beneficiary" class="field">
          <label>Name of the Beneficiary</label><br>
          <%= text_field_tag('preferences[company_beneficiary]', Spree::Company::Config[:company_beneficiary], :size => 40) %>
        </div>

        <div data-hook="company_bankname" class="field">
          <label>Name of the Bank </label><br>
          <%= text_field_tag('preferences[company_bankname]', Spree::Company::Config[:company_bankname], :size => 40) %>
        </div>
       
       <div data-hook="company_branchname" class="field">
          <label>Bank Branch</label><br>
          <%= text_field_tag('preferences[company_branchname]', Spree::Company::Config[:company_branchname], :size => 40) %>
        </div>
       <div data-hook="company_account_number" class="field">
          <label>Bank Account Number</label><br>
          <%= text_field_tag('preferences[company_account_number]', Spree::Company::Config[:company_account_number], :size => 40) %>
        </div>
       <div data-hook="company_rtgscode" class="field">
          <label> BANK RTGS CODE</label><br>
          <%= text_field_tag('preferences[company_rtgscode]', Spree::Company::Config[:company_rtgscode], :size => 40) %>
        </div>



      </div>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:update), 'icon-refresh' %>
      </div>

    </fieldset>

<% end -%>

extensions/spree_invoicing-master/app/views/spree/admin/orders/_print_buttons.html.erb
<% if @order and @order.completed_at? %>
  <% buttons = Spree::PrintInvoiceConfig[:print_buttons]
     buttons = buttons.split(",").collect{|b| b.strip } %>
  <%  buttons.each do |button| %>
   <%= button_link_to(Spree.t(button.to_s + "_print"), spree.order_path(@order, :pdf )) %>
    

  <% end %>
<% end %>  

extensions/spree_invoicing-master/app/views/spree/admin/orders/_print_buttons1.html.erb
<hr>

 <div class="form-buttons" style="padding:20px;font-style:italic;font-size:20pt; a{color:#fff}">
    <%=  link_to Spree.t("Bulk PDF Generation"), admin_orders_path( :format => "pdf") %>
 </div>

<hr>

extensions/spree_invoicing-master/app/views/spree/admin/orders/_print_buttons2.html.erb
<br>

<% if @order and @order.completed_at? %>
  <% buttons = Spree::PrintInvoiceConfig[:print_buttons]
     buttons = buttons.split(",").collect{|b| b.strip } %>
  <%  buttons.each do |button| %>
   <%= button_link_to(Spree.t(button.to_s + "_print"), spree.order_path(@order, :pdf )) %>
  

  <% end %>
<% end %>  
<hr>